### ISSUE TITLE
Get-CECloudRegion Error 

### ISSUE THREAD

**Issue by shubhamgupta514** [bamcisnetworks/CloudEndure#1]
@hakenmt  - In CloudEndure.psm1 ,Please correct line No. 7204 in Get-CECloudRegion function.

#######Incorrect#########
$Id = $Project.source
#######################

#########Correct#########
$Id = $Project.sourceRegion
#######################

Reason : $Project = Get-CEProject -Id $ProjectId -Session $Session

The project object does not source property instead of that sourceRegion is there.

There are many other issues in the module that I identified myself. I will keep you updated  time to time.

**Comment by hakenmt** [comment]
This is probably a disparity between v12 of the API and v15 aka v3 of the API. In the current documentation,  you are correct, it does list the response to /projects/projectId with "sourceRegion", however, for v12 documentation: 
![image](https://user-images.githubusercontent.com/17982823/34910089-458cbe20-f87c-11e7-8edf-c05c975d19fc.png)

I'll need to decide on whether to make the Get-CEProject response consistent across versions of whether to make the property calls to the response version dependent.

Please let me know of all the issues you find, unfortunately my active accounts with CE are only v12 right now. Thanks.

**Comment by shubhamgupta514** [comment]
In Line 11014 ,Get-CEWindowsInstaller   : Datatype is incorrect and need PassThru to store the result.

######Incorrect###########################
[Microsoft.PowerShell.Commands.HtmlWebResponseObject]$Result = Invoke-WebRequest -Uri $script:Installer -OutFile $Destination -ErrorAction Stop
########################################

######Correct###########################
[Microsoft.PowerShell.Commands.WebResponseObject]$Result = Invoke-WebRequest -Uri $script:Installer -OutFile $Destination -ErrorAction Stop -PassThru
########################################

**Comment by shubhamgupta514** [comment]
in Line 729, Remove-CESession

#######Incorrect##########################
$Uri = "$($SessionInfo.Url)/logout"
########################################

######Correct#############################
$Uri = "$($SessionInfo.Values.Url)/logout"
########################################

**Comment by shubhamgupta514** [comment]
In Line 8856, Start-CEDataReplication

##############Incorrect#############
Write-Verbose -Message "Replication successfully stopped for machine(s) $([System.String]::Join(",", $($Result | Select-Object -ExpandProperty Items | Select-Object -ExpandProperty Id)))."
##################################

#############Correct###############
Write-Verbose -Message "Replication successfully started for machine(s) $([System.String]::Join(",", $($Temp| Select-Object -ExpandProperty Items | Select-Object -ExpandProperty Id)))."
##################################

**Comment by shubhamgupta514** [comment]
@hakenmt  - All above are the bugs that I found in the module till now.

**Comment by shubhamgupta514** [comment]
@hakenmt  Is there any ETA for the new release???

**Comment by hakenmt** [comment]
I'm going to try and get to them this week, it's been a very busy few weeks at work, but hopefully should have some time soon. Appreciate your patience.
