### ISSUE TITLE
Command for test/cutover 

### ISSUE THREAD

**Issue by panhvr** [bamcisnetworks/CloudEndure#10]
Hi Mike 

Which command to use for perform cutover for a replication server to AWS (incase of migration).

Invoke-CELaunchTargetMachine
Invoke-CEMachineCutover

I tried both above commands but both fails with an error below 

The project 312345af-8b46-42d2-9678-be0f99c5bb74 cannot be reversed.

Please advise

**Comment by hakenmt** [comment]
In the new release, it's `Invoke-CELaunchTargetMachine` and you provide a parameter to `LaunchType`, in this case it would be `CUTOVER`.
