### ISSUE TITLE
Unable to run in PS Core 6.2.3

### ISSUE THREAD

**Issue by CarltonW** [bamcisnetworks/CloudEndure#11]
Thank you for creating this module. I have AWS instances that we need to shutdown at night. Your module is the only solution that allows me to suspend sync and start again in the AM.

I can run $Email = New-CESession -ProfileName Lab -PassThru fine from PS 5.1, but errors out from PS Core 6.2.3 with:

You cannot call a method on a null-valued expression.
At C:\Users\cwhitmore\Documents\PowerShell\Modules\CloudEndure\2.0.0\CloudEndure.psm1:1139 char:5
+ ...             [System.String]$Url = $Result.BaseResponse.ResponseUri.To ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\cwhitmore\Documents\PowerShell\Modules\CloudEndure\2.0.0\CloudEndure.psm1:1141 char:9
+                 if ($Url.EndsWith("latest"))
+                     ~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvokeMethodOnNull

Exception calling "GetCookies" with "1" argument(s): "Value cannot be null.
Parameter name: uri"
At C:\Users\cwhitmore\Documents\PowerShell\Modules\CloudEndure\2.0.0\CloudEndure.psm1:1180 char:5
+ ...             [System.Net.CookieCollection]$Cookies = $WebSession.Cooki ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : ArgumentNullException

There was an issue retrieving the account summary:
At C:\Users\cwhitmore\Documents\PowerShell\Modules\CloudEndure\2.0.0\CloudEndure.psm1:5492 char:4
+             throw "There was an issue retrieving the account summary: ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (There was an issue \u2026e account summary: :String) [], RuntimeException
+ FullyQualifiedErrorId : There was an issue retrieving the account summary:

**Comment by hakenmt** [comment]
Two quick questions, do you know what version of the CloudEnure APIs your account is using? When you login to the console, there should be a header that is returned, X-CloudEndure-Version, which you can inspect in your browser. Also, just want to confirm that you have created a profile first named "Lab"?

From the exception, I can't tell whether the `$Result` variable itself is null or if it's one of its members. Could you edit the module just before line 1139 and try writing the `$Result`, `$Result.BaseResponse` and `$Result.BaseResponse.ResponseUri` to the console, something like:
    
    Write-Host ($Result | Out-String)
    Write-Host ($Result.BaseResponse | Out-String)
    Write-Host ($Result.BaseResponse.ResponseUri | Out-String)

That would be super helpful in debugging what is causing the error for you.

**Comment by hakenmt** [comment]
Closing.
