### ISSUE TITLE
Query: Rest API/Cmdlet

### ISSUE THREAD

**Issue by shubhamgupta514** [bamcisnetworks/CloudEndure#3]
@hakenmt  - Is there any api/cmdlet available to fetch below information for replicated machine?

![image](https://user-images.githubusercontent.com/12984945/35729574-2b8e912e-0835-11e8-8b47-1125af8a0a9b.png)

**Comment by hakenmt** [comment]
I think the cmdlet you want is Get-CEMachine -Id $MachineGuid. The Tested/Launched information should be under the lifeCycle property. The lag I think is under the replicationInfo > backloggedStorageBytes property. The UI I think is just summarizing/translating that data to show that info and compute the Lag time into minutes.

**Comment by Suresh8811** [comment]
@hakenmt -
Trying to create newproject using New-CEProject but getting error while passing parameter replicationConfiguration where i can find this ID?, could you pls let me know the right parameter used for creating NewProject
