### ISSUE TITLE
NewProject Issue

### ISSUE THREAD

**Issue by hakenmt** [bamcisnetworks/CloudEndure#4]
@suri78 Trying to create newproject using New-CEProject but getting error while passing parameter replicationConfiguration where i can find this ID?, could you pls let me know the right parameter used for creating NewProject.

I opened this as a new issue.

**Comment by hakenmt** [comment]
When you create a replication configuration with `New-CEReplicationConfiguration` and use the `-PassThru` parameter, one of the properties returned to the pipeline in the `PSCustomObject` is `id`. Or you can call `Get-CEReplicationConfiguration` and find the replication configuration that has already been created that you want to use with the project.

**Comment by Suresh8811** [comment]
@hakenmt - tried using replication configuration id that has already been created & used  New-CEProject -Source "Generic" -Target "AWS" -Name "AWS-Migration" -ReplicationConfiguration xxxxxxxxxxxxxxxxxx but had below issue

There was an issue creating the project: 0 Invalid URI: The hostname could not be parsed. - 
At C:\Program Files\WindowsPowerShell\Modules\CloudEndure\1.2.1.0\CloudEndure.psm1:5403 char:7
+ ...             throw "There was an issue creating the project: $StatusCo ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (There was an is...t be parsed. - :String) [], RuntimeException
    + FullyQualifiedErrorId : There was an issue creating the project: 0 Invalid URI: The hostname could not be parsed. -

**Comment by hakenmt** [comment]
Have you setup credentials and then a session with `New-CESession` first? Take a look at the readme, it explains some of the cmdlets you need to use to get started.

**Comment by Suresh8811** [comment]
yes I have and used -PassThru , I get other project details including two of my replication settings but not sure why it is not getting my session.. let me go through it again
