### ISSUE TITLE
Use with API token instead of name and password

### ISSUE THREAD

**Issue by ramschel** [bamcisnetworks/CloudEndure#5]
Is there a way to use these functions with an API token instead of a name/password session?

**Comment by hakenmt** [comment]
When I originally developed this module several years ago there was only the ability to sign in via username/password. I haven't kept up with recent changes in the CE APIs. If you could provide a link to the documentation showing how to use the API token, I can evaluate the feasibility of integrating that feature.

**Comment by ramschel** [comment]
I reviewed:  https://console.cloudendure.com/api_doc/apis.html#tag/authentication%2Fpaths%2F~1login%2Fpost

Using my API token and cribbing some of your code, I can get a 200 response with expected CloudEndure account details:

$postParams = @{userApiToken='\<API Token\>'}  
$json = $postParams  | ConvertTo-Json

$Url="https://console.cloudendure.com/api/latest"

[Microsoft.PowerShell.Commands.HtmlWebResponseObject]$Result = Invoke-webrequest -Uri "$Url/login" -Method Post -SessionVariable WebSession -Body $json -ContentType "application/json"

[System.String]$Url = $Result.BaseResponse.ResponseUri.ToString().Substring(0,  $Result.BaseResponse.ResponseUri.ToString().LastIndexOf("/"))
[Microsoft.PowerShell.Commands.WebRequestSession]$WebSession = $WebSession
[System.Net.CookieCollection]$Cookies = $WebSession.Cookies.GetCookies($Url)
[System.Net.Cookie]$MatchingCookie = $Cookies | Where-Object {$_.Name -ieq "XSRF-TOKEN"} | Select-Object -First 1
$WebSession.Headers.Add("X-XSRF-TOKEN", $MatchingCookie.Value)

[Microsoft.PowerShell.Commands.HtmlWebResponseObject]$ProjectsResponse = Invoke-WebRequest -Uri "$Url/projects" -WebSession $WebSession -Method Get -ErrorAction Stop 

$ProjectsResponse.RawContent

**Comment by hakenmt** [comment]
Ok, I may have some free time in the coming weeks to add this in.

**Comment by hakenmt** [comment]
Should be available in newest release.
