### ISSUE TITLE
New-DynamicParameter

### ISSUE THREAD

**Issue by duhaas2015** [bamcisnetworks/CloudEndure#6]
Not so much an issue but more of an education, I'm attempting to creating my new-cesession using -passthru and while doing do i'm running into an issue where it complaining about New-DynamicParameter not being the recognized name of a commandlet.  Can you please educate me on where I can find that function please?

**Comment by hakenmt** [comment]
That function is part of BAMCIS.DynamicParam. It looks like at some point I moved the New-DynamicParameter out of the BAMCIS.Common module, but did not update the manifest for this module to reflect that. I'll get that fixed.

**Comment by hakenmt** [comment]
I've updated the BAMCIS.Common module published to PowerShell Gallery as well as the manifest for this module. That should fix your issue, sorry about that.

**Comment by duhaas2015** [comment]
appreciate you doing that, thanks a bunch!!!!!!
