### ISSUE TITLE
set-ceblueprint where are the parameters

### ISSUE THREAD

**Issue by duhaas2015** [bamcisnetworks/CloudEndure#7]
Have established my connection, am able to query and return various result, issue I'm running into is when I go to leverage set-ceblueprint, many of the dynamic parameters such as -IAMRole come back as "a parameter cannot be found that maches parameter name 'IAMRole'.  I'm sure its something i'm doing wrong, curious to know what.  Thanks for the assist.

**Comment by hakenmt** [comment]
Sorry I didn't respond to this, did you manage to get this resolved? Was your target cloud set to AWS?

**Comment by duhaas2015** [comment]
Yeah, not sure what my early issue was, but after I got past that, the only thing I was running into was:  

"The cloud environment 6849e59c-29f5-4e10-a459-9d8584c7524b is not supported by this cmdlet yet"

I ended up just updating the switch statement to use that vs. "AWS" not sure if ID's have changed, not sure, but after updating the switch statement I'm good.

**Comment by hakenmt** [comment]
Ah, so the "Cloud" property from "Get Region" API call used to return the name of the cloud, like "AWS". It appears now that the API defines that property to be a UUID, in particular, a UUID that is different from the one they used to use for AWS. I can update the main module to fix that, there's at least 2 places that use the same logic.

**Comment by duhaas2015** [comment]
That would be awesome, I'm too big of a newb to submit a pull request for that, although i'm getting close.  still trying to figure out what your doing with that @DynSplat after the Get-CETargetCloud.  I've obviously hacked it enough to get it to work for now.

**Comment by hakenmt** [comment]
The @VariableName syntax is called splatting. You create a HashTable whose key value pairs are parameters to a cmdlet with their values. This way you can build a dynamic set of parameters and only write the actual call to the cmdlet once, it's a way of reducing the amount of code you need to write. I think in the case you're looking at:
```
    $DynSplat = @{
        "Session" = $DynSession
    }
    ...
    Get-CETargetCloud @DynSplat
```

Instead of supplying the variable "DynSplat" with the "$" prefix, you use the @ sign to indicate it's a splat. Thus, you can use conditional logic to selectively add parameters to the hashtable, which could end up being empty, and supply it to the cmdlet.

[Splatting Documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-6)

**Comment by duhaas2015** [comment]
thats awesome, really appreciate you taking the time to explain.  if you get around to making the changes, let me know, i'm happy to test it out.

**Comment by panhvr** [comment]
Hello All,

I am trying to use the module for migrating VM from on-prim to AWS.

I managed to establish connection to CloudEndure, but getting error while creating new blueprint and updating blueprint to machine.

Could you please help me in updating the blueprint.

Regards

**Comment by aspersram** [comment]
Good day:  I'm trying to set CE blueprints but I'm having difficulties doing it.  Can you show me the proper syntax for setting it? 
Below is my statement/error:

set-ceblueprint -instanceid 35a1773e-3acb-471d-af7c-723facaxe9b -InstanceType "t2.micro"
Set-CEBlueprint : Cannot retrieve the dynamic parameters for the cmdlet. The cloud environment 6849e59c-29f5-4e10-a459-9d8584c7524b is not supported by this cmdlet yet.
At line:1 char:1
+ set-ceblueprint -instanceid 35a1773e-3acb-471d-af7c-723facaxe95b -Ins ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-CEBlueprint], ParameterBindingException
    + FullyQualifiedErrorId : GetDynamicParametersException,Set-CEBlueprint
