### ISSUE TITLE
set-ceblueprint (multiple disks)

### ISSUE THREAD

**Issue by duhaas2015** [bamcisnetworks/CloudEndure#8]
Can you please help educate me on how to specify multiple disks in the set-ceblueprint?

   set-ceblueprint `
        -InstanceId $machine.id `
        -IAMRole "Role-EC2-RO" `
        -SubnetIDs "subnet-24f4a44d" `
        -InstanceType "t2.micro" `
        -SecurityGroupIDs "sg-02729a07736a4b5c8" `
        -StaticIP DONT_CREATE `
        -PublicIPAction DONT_ALLOCATE `
        -PrivateIPAction CREATE_NEW `
        -Disks @{type = "SSD"; name = "/dev/sda"}`
        -Force:$true
   }

Happy to submit pull request for adding to the get-help documentation once I can confirm

**Comment by hakenmt** [comment]
The `Disks` parameter is an array of hash tables:
`-Disks @(@{type = "SSD"; name = "/dev/sda"}, @{type="SSD"; name = "/dev/sdb"})`
Each hashtable represents a different disk. The `@( )` syntax is used to represent an array, you could also just comma separate the hash tables and it will be interpreted as an array that way as well.

**Comment by duhaas2015** [comment]
this is great, getting closer, getting a 400 bad request, will dig into that issue now.

**Comment by duhaas2015** [comment]
appears it has to do with the name value being picky, looking at their default that gets created:  

name = "c:0" is happy
