### ISSUE TITLE
Set-CEBlueprint fails for AWS

### ISSUE THREAD

**Issue by remenaker** [bamcisnetworks/CloudEndure#9]
When using Set-CEBlueprint and you are replicating to AWS, the function fails every time with this message. 

> Set-CEBlueprint : Cannot retrieve the dynamic parameters for the cmdlet. The cloud environment <GUID> is not supported by this cmdlet yet. At line:1 char:1

Looking at the function certain items are modified based on the target environment. This is determined by switching the cloud property from the function Get-CETargetCloud. This is a Cloud for my environment. The name of the environment is in the property name. For AWS this includes the region as well. For example "AWS Canada (Central)"

**Comment by hakenmt** [comment]
Unfortunately, CloudEndure has significantly changed some of its APIs over time and I haven't been keeping up with them. Doing a major update to the entire module is on my roadmap.

**Comment by panhvr** [comment]
> When using Set-CEBlueprint and you are replicating to AWS, the function fails every time with this message.
> 
> > Set-CEBlueprint : Cannot retrieve the dynamic parameters for the cmdlet. The cloud environment  is not supported by this cmdlet yet. At line:1 char:1
> 
> Looking at the function certain items are modified based on the target environment. This is determined by switching the cloud property from the function Get-CETargetCloud. This is a Cloud for my environment. The name of the environment is in the property name. For AWS this includes the region as well. For example "AWS Canada (Central)"

**Comment by panhvr** [comment]
Hello,

I managed to establish session to CE and able to result for some of the get commands.
Now I think I need to look for"new-ceblueprint and set-ceblueprint"  to update blueprint for each replicated VM. When I am trying  "new-ceblueprint"  I am getting " Cannot retrieve the dynamic parameters for the cmdlet. The cloud environment is not supported by this cmdlet yet"

If you have tried most of the functions, could you please guide me where exactly I need to update

**Comment by hakenmt** [comment]
This should be fixed in the latest release.
